default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || ENV['POSTGRES_PORT'] || 5432 %>
  pool: <%= ENV['POSTGRES_POOL'] || 100 %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB_NAME'] || 'pb_hiring_development' %>

test:
  <<: *default
  database: pb_hiring_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

